apiVersion: apps/v1
kind: Deployment
metadata:
  name: daisy-sample-httpd-app
  namespace: daisy-eks-activity38
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd-app
  template:
    metadata:
      labels:
        app: httpd-app
    spec:
      containers:
        - name: httpd-app
          image: hashicorp/http-echo:latest
          args:
            - "-text=$(WELCOME_MESSAGE)"
          ports:
            - containerPort: 5678
          env:
            - name: WELCOME_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: sample-config
                  key: welcome-message
            - name: APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sample-secret
                  key: password
