apiVersion: v1
kind: Service
metadata:
  name: daisy-clusterip-service
  namespace: daisy-eks-activity38
spec:
  type: ClusterIP
  selector:
    app: httpd-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5678
