apiVersion: v1
kind: Service
metadata:
  name: daisy-loadbalancer-service
  namespace: daisy-eks-activity38
spec:
  type: LoadBalancer
  selector:
    app: httpd-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
